### ISSUE TITLE
How to use info_box / app_btn / box_open helper in frontend ?

### ISSUE THREAD

**Issue by januarfonti** [waifung0207/ci_bootstrap#13]
Hello, How to use info_box / app_btn / box_open helper in frontend ?
When i use it, there is some error message

Fatal error: Call to undefined function info_box() in C:\xampp\htdocs\komoditas\applications\frontend\views\detail_bahanpokok.php on line 43

Thanks

**Comment by waifung0207** [comment]
Hi,

You can copy the code from Backend's MY_html_helper (location: applications/backend/helpers/MY_html_helper.php) to Frontend's MY_html_helper.

But beware that, Frontend & Backend are using different stylesheets (e.g. Backend is using AdminLTE, while Frontend is using plain Bootstrap only), so functions like info_box() will not display the same as what you see from Backend system. 

In case you really want the AdminLTE styling to display on Frontend website, you will need to update /gulpfile.js and merge the AdminLTE stylesheets into Frontend, then run the gulp task again.
