### ISSUE TITLE
Update to CI 3.0

### ISSUE THREAD

**Issue by r4z01** [waifung0207/ci_bootstrap#4]
Even better if we can update whole project to CI 3

**Comment by waifung0207** [comment]
Indeed! Actually I am working on a new repository from here:
https://github.com/waifung0207/ci_bootstrap_3

The reason for separating from old repo is there are quite a lot of structure changes. While the new repo will have much enhancements (e.g. classes like models and helpers can be shared among different sites), I am going to take this chance to refactor some codings so developers can be easier to customize for their sites.

The new repo is still in progress but I am going to push it to more stable state within this month, with documentation about how to make use of it, so please stay tuned on that :)
