### ISSUE TITLE
Unable to load the requested language file: language/english/general_lang.php

### ISSUE THREAD

**Issue by CdaGanache** [waifung0207/ci_bootstrap#6]
Hi Waifung..thanks for the great code.. may i know why i face this problem if i want to access the frontend.

Unable to load the requested language file: language/english/general_lang.php

**Comment by waifung0207** [comment]
Hi CdaGanache,

Did you make any changes after the first clone?

You can check if the value from your config file (applications/frontend/config/config.php) and find out this line: $config['language']  = 'en';
The value above should match with the language name under: applications/frontend/language/

Alternatively, you can also create a folder as: "applications/frontend/language/english/" and create an empty file "general_lang.php" inside that folder, then see if the problem can be solved.

**Comment by CdaGanache** [comment]
ok..thanks it's work.. by the way i have so much problem with my system that i developed right now.. i'm using grocery crud and have so much problem to integrate with  login and  pdf to generate reports.. i'm using mpdf library to create .pdf file. but it won't works.. i failed to call some field from database also failed to create login page.. the login must not integrate with emel just a simple login but i failed to do the best..i'm stuck right now and the dateline is around the corner. do you have any good idea how can i try to solve it . ='(

**Comment by waifung0207** [comment]
First of all, I suggest you need to figure out the problem causes and know how to debug at this first steps, as you are telling quite a lots of problems here, and you better handle them one by one. 

When you say something doesn't work, I think at least you need to describe the error you are encountering (even a blank page, or 403 error, etc.), and I suggest you to make use of Developer Tool from browser (e.g. Firefox, Chrome) to see if they provide more messages to you. 

If you need to see more PHP error messages, you can call some functions like this: 

``` php
ini_set('display_errors',1);
ini_set('display_startup_errors',1);
error_reporting(E_ALL);
```

Back to your question, Grocery Crud should have nothing done with your login page, and you should solve the login issue without using Grocery Crud first. Right now I don't have any good suggestion on PDF export library yet, so sorry for this.

**Comment by CdaGanache** [comment]
ok.. thanks so much then.. i will try phase by phase after this.. thanks yaa =')

**Comment by CdaGanache** [comment]
Hi there.. i had fixed the problem 70% and success to combine your codes and mine. =')
Before this in my page i have export and print button..but when i combine the button doesn't appear.. can you please help me to explain how to make the button appear again? thanks in advance =')

**Comment by waifung0207** [comment]
You will find some code from: applications/backend/helpers/crud_helper.php where I have disabled them by calling unset_print() and unset_export() by default. To enable them again, just comment out the lines and should be fine.

**Comment by CdaGanache** [comment]
yeayyyyyyyyyyyy!!!!!!!!!!!!! i found it and it works!! thanksssssss Michael Chan!! =')

**Comment by waifung0207** [comment]
You're welcome :)
I am closing this issue now and hope you will do well in your project.
